algoritmo "SomaParametrosReferencia"
//Passagem por valor a variável global não muda
//Passagem por referência a variável global muda (var)
var
   X, Y: Inteiro
Procedimento Soma (var A, B: Inteiro)
inicio
   A <- A + 1
   B <- B + 2
   Escreval("Valor de A = ", A)
   Escreval("Valor de B = ", B)
   Escreval("Soma A + B = ", A+B)
FimProcedimento
Inicio
   X <- 4
   Y <- 8
   Soma (X, Y)
   Escreval("Valor de X = ", X)
   Escreval("Valor de Y = ", Y)
fimalgoritmo
